### ISSUE TITLE
FFI_LIB for ubuntu

### ISSUE THREAD

**Issue by ifeech** [quasilyte/kphp-sdlite#1]
I wanted to test this game with php: https://github.com/quasilyte/kphp-game
Use make command I had **PHP Fatal error:  Uncaught FFI\Exception: Failed loading 'libSDL2_ttf-2.0.so' in ** 
I installed libs of libSDL2_ from apt install. The problem saved.

I found a problem: 
ubunty `$ locate libSDL2_ttf-2.0`
`/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0`
`/usr/lib/x86_64-linux-gnu/libSDL2_ttf-2.0.so.0.14.1`

I changed all FFI_LIB to libSDL2_*-2.0.so.**0**

It works!

**Comment by quasilyte** [comment]
Since it's not a production-quality game, the distribution parts are messy. We're trying to find the local library in a naive way, by a hardcoded name.

I think your suggestion can be helpful for people that would like to try it out though, so thank you for reporting it.

As a side note, I think a better and portable solution would be:
* Inside installer step (that we don't have) locate the libraries
* Add local symlincs to them, so they're named as FFI C files expect (without suffixes)
* Add a launcher script that runs the game with LD_LIBRARY_PATH set to the local dir with symlincs

This installation+launcher setup should also work for macos, where libraries may have a `dylib` suffix. As long as we reference the right libs, everything should work fine. For Windows, I guess the common practice is to bundle the DLLs with the game itself (?).

This is necessary since FFI C files reference a library by its name directly and can't be smarter or replaced at the run time.

**Comment by ifeech** [comment]
Yes. This issue was created to help people.
Thanks for your solution!
